# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d5777db8417c9129d13d95a4e262d6ab20e411e7fac475cb76b6ce5e1f4b897920c26502dc5bddd688dc7c28d1b6018b2538fe1bd1788fb2e381fa117cc5cb08

test:
  secret_key_base: e641e7df34c91c0b2855a8cfcc737a279c482d4dd432a69f907bb5fb64a9b5ed2e5491d5cc97b5dd944da3aca931f5e1c71d75d87b11a76b64a1ec78cb3acf20

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
